### ISSUE TITLE
How to incorporate a new string search algorithm in your benchmarks?

### ISSUE THREAD

**Issue by ghost** [almondtools/net.amygdalum#1]
Hi,

I have invented a new string search algorithm and I would like to include that in your benchmarks to see how efficient my algorithm is.

Please let me know what to do.

Please contact me at amitchoudhary0523@gmail.com.

My algorithm can be downloaded from here: https://sourceforge.net/projects/algorithms-in-java/files/New_String_Search_Algorithm.java/download

Regards,
Amit

**Comment by almondtools** [comment]
I sent you a mail with hints.

Further issues with [stringbench](https://github.com/almondtools/stringbench) are better placed here: https://github.com/almondtools/stringbench/issues.

**Comment by ghost** [comment]
Hi Stefan,

I have invented the fastest string search algorithm.

I did an experiment with a very long text and a short pattern.
found here
My algorithm beats BoyerMoore algorithm easily.

Will you integrate my algorithm in your tests?

The source code and details of the experiment can be found here:

https://sourceforge.net/projects/fastest-string-search-algo/files/

Regards,
Amit

**Comment by almondtools** [comment]
I shall be able to integrate your algorithm if you provide:

- your a Benchmark class that extends SinglePatternMatcherBenchmark
- your a Test class that extendsSinglePatternMatcherBenchmarkTest

Feel free to provide a complete pull request. Note that this issue is already closed (It is filtered from my view in github). So please post/reopen an issue on stringbench here https://github.com/almondtools/stringbench/issues and add your implementation (or attach the pull request).

**Comment by ghost** [comment]
Hi Stefan,

Do you have a java file that does that already for some algorithm. If you
can point me to one then I will just download it and replace the algorithm
in it by my algorithm.

Regards,
Amit

**Comment by almondtools** [comment]
[stringbench](https://github.com/almondtools/stringbench) contains examples.

Another hint: Your algorithm is of complexity O(n²). It is very likely that it beats your Boyer-Moore-Implementation (which is O(n) or sublinear on average) because it is implemented in an imperformant way. A quite fast implementation of Boyer-Moore is contained in the java standard library if you compile a literal pattern with

```
Pattern p = Pattern.compile("pattern");
Matcher m = p.matcher("haystack ..."); 
while (matcher.find()) {... }
```

An example for a benchmark for this algorith could be found here: https://github.com/almondtools/stringbench/blob/master/src/main/java/com/almondtools/stringbench/singlepattern/jdk/JavaRegexBenchmark.java

**Comment by ghost** [comment]
Hi Stefan,

I will compare my algo with java boyer moore implementation.

In our day to day search which we encounter every day (searcing for some
text in a file, web page, etc.), my algorithm will likely out perform other
algorithms because the probability of elements of pattern matching the
corresponding elements of text (at pisition 0, n-1, n/2, n/4, 3n/4) and the
whole string not matching is very very less.

n is the length of pattern.

Theoritically, it may look like O(n^2) but practically it is faster than
other algorithms.

Just because something looks good on paper doesn't mean that it will be the
best.

Regards,
Amit

**Comment by ghost** [comment]
Hi Stefan,

I just included Java Regex search (pattern/matcher) and it does not perform
as well as my algorithm. Please find the results below:

Also, the implementation of Boyer Moore algo in my program (I took it from
internet) is faster than Java Regex search.

Pattern found at index 30384

=====================Result=====================

Time taken by Brute Force algorithm = 62,167,600 ns.
Time taken by Boyer Moore algorithm = 29,604,300 ns.
Time taken by Rabin Karp algorithm = 635,027,800 ns.
Time taken by Knuth Morris Pratt algorithm = 59,525,200 ns.
Time taken by Java Regex Pattern Matching algorithm = 43,196,800 ns.
Time taken by Choudhary algorithm = 17,216,200 ns.

Choudhary string search algorithm is the fastest.

=====================End of Result=====================

Regards,
Amit

**Comment by almondtools** [comment]
It is just an unfair match. 

**Common algorithms** are designed to search well all matches in several documents. This is done by preprocessing the pattern and applying the preprocessed pattern to all documents repeatedly. The effort for preprocessing is only once and processing thousands of documents with thousands of words will make it irrelevant for performance.

**Your benchmark** deviates from this 
- in stopping after the first match
- not applying the pattern to several documents

By searching only until the first match in exactly one document the effort of preprocessing is distributed to exactly one search. This means: you are not measuring the search performance but the preprocessing performance of the pattern.

To get an impression of the pure search performance of boyer moore, just move `Pattern.compile` out of your ` for (int i = 0; i < 1000; i++)`.

Maybe you are not convinced. Nevermind. Just clone stringbench and add your algorithm. And create a pull request after convincing yourself.

**Comment by ghost** [comment]
Hi Stefan,

Ultimately, all searches are reduced to calling a function and a function
will not keep the state of the algorithm for the next search.

For example, if we look at the function strstr() of glibc, it doesn't keep
any state of the algorithm it uses.

So, everytime it is called, it will do the preprocessing again.

Regards,
Amit

**Comment by ghost** [comment]
Hi Stefan,

As you said, I moved Pattern.compile(pattern); out of the for loop. But
still my algorithm is the fastest. Please find the results below:

=====================Result=====================

Time taken by Brute Force algorithm = 60,665,300 ns.
Time taken by Boyer Moore algorithm = 25,905,100 ns.
Time taken by Rabin Karp algorithm = 621,152,500 ns.
Time taken by Knuth Morris Pratt algorithm = 58,476,300 ns.
Time taken by Java Regex Pattern Matching algorithm = 26,104,800 ns.
Time taken by Choudhary algorithm = 17,295,300 ns.

Choudhary string search algorithm is the fastest.

=====================End of Result=====================

Regards,
Amit

**Comment by almondtools** [comment]
Obviously we do not agree on the purpose of stringsearch algorithms. The results of your test are reproducible but the conclusion is not valid in general (see above).

However it was not really much work to implement the Benchmark classes for your algorithm and to get some test results:

[TestResults.zip](https://github.com/almondtools/net.amygdalum/files/6604996/TestResults.zip) contains the implementations and the eclipse testreports (also containing the times).

Result: The algorithm seems not to cover all edge cases (some searches simply fail to find all occurences, see the stack traces). The others are slower than brute force on average (`String.indexOf` is brute force). You will need to checkout stringbench to debug this. It is open to you to correct it and to tune it.

**Comment by ghost** [comment]
Hi Stefan,

I will implement my algorithm to search for multiple occurrences and then
send you the code.

I will also see the test results that you have sent.

Regards,
Amit

**Comment by ghost** [comment]
Hi Stefan,

Just to make a point.

Rabin Karp algo is O(n) on paper and brute force is O(n^2) on paper.

But brute force almost everytime outperforms rabin karp algo.

This is just to emphasize my point that something that looks good on paper
may not be as good in real life practical scenarios.

Regards,
Amit

**Comment by ghost** [comment]
Hi Stefan,

Please don't include my algorithm in your framework. I am developing a
framework of my own to compare different string search algorithms.

Regards,
Amit
